version: "3"
services:
  owncast:
    image: owncast/owncast:latest
    expose:
      - "8080"
    ports:
      - "1935:1935"
    volumes:
      - /home/user/owncastdata:/app/data
    restart: unless-stopped

  caddy:
    image: caddy:latest
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    restart: unless-stopped

volumes:
  caddy_data:
  caddy_config:

